import Head from 'next/head'
import Avatar from "@/Components/Avatar";
import {Squares2X2Icon} from "@heroicons/react/20/solid";


export default function Home() {
  return (
    <>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*Header*/}
        <header className={'flex w-full p-5 justify-between text-sm text-gray-700'}>
            {/*Header Left*/}
            <div className={'flex space-x-4 items-center'}>
                <p className={'link'}>About</p>
                <p className={'link'}>Store</p>
            </div>
            {/*Header Right*/}
            <div className={'flex space-x-4 items-center'}>
                <p className={'link'}>Gmail</p>
                <p className={'link'}>Images</p>
                {/*Icon*/}
                <Squares2X2Icon className={'h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'}/>
                {/*Avatar*/}
                <Avatar url={'https://coaching.papareact.com/ai9'}/>
            </div>

        </header>
        {/*Body*/}
        {/*Footer*/}


    </>
  )
}
